version: "3.9"
services:
  api:
    build:
      context: .
      target: dev
    container_name: auth_api
    env_file:
      - .env
    restart: always
    ports:
      - 8080:${API_PORT}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.0
    container_name: auth_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    
volumes:
  postgres:
